version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: failbnbdb
  
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: failbnbdb
    depends_on:
      - db
    volumes:
      - ./backend:/app

    command: ["sh", "./wait-for.sh", "db", "npm", "start"]

  frontend:
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:
